import { buildPlayerRecap } from "@/lib/player-recap";
import { safeHex } from "../../route-utils";
import { trackOperationalEvent } from "@/lib/telemetry";

export const runtime = "nodejs";

interface RouteContext {
  params: Promise<{ playerId: string }>;
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function svgResponse(svg: string, status = 200) {
  return new Response(svg, {
    status,
    headers: {
      "Content-Type": "image/svg+xml; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=900",
    },
  });
}

function cut(value: string, max: number) {
  if (value.length <= max) return value;
  return `${value.slice(0, max - 1)}...`;
}

export async function GET(_request: Request, context: RouteContext) {
  const { playerId } = await context.params;

  try {
    const recap = await buildPlayerRecap(playerId);

    if (!recap) {
      return new Response("Not found", { status: 404 });
    }

    const primary = safeHex(recap.team.primaryColor, "#1d7a61");
    const secondary = safeHex(recap.team.secondaryColor, "#0f172a");
    const recentBadge = recap.lastFive.matches > 0
      ? `${recap.lastFive.goals}G ${recap.lastFive.assists}A nos ultimos ${recap.lastFive.matches}`
      : "Sem partidas recentes";

    trackOperationalEvent("recap_player_card_viewed", {
      playerId,
      teamId: recap.team.id,
      matches: recap.career.matches,
    });

    const playerName = escapeXml(cut(recap.player.name, 28));
    const teamName = escapeXml(cut(recap.team.name, 42));
    const badge = escapeXml(cut(recentBadge, 44));

    const svg = `
      <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
        <defs>
          <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stop-color="${primary}" />
            <stop offset="100%" stop-color="${secondary}" />
          </linearGradient>
          <linearGradient id="glass" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stop-color="rgba(255,255,255,0.22)" />
            <stop offset="100%" stop-color="rgba(255,255,255,0.08)" />
          </linearGradient>
        </defs>
        <rect width="1200" height="630" fill="url(#bg)" />
        <circle cx="1080" cy="-80" r="320" fill="rgba(255,255,255,0.08)" />
        <circle cx="130" cy="140" r="220" fill="rgba(255,255,255,0.10)" />
        <rect x="36" y="34" width="1128" height="562" rx="30" fill="rgba(0,0,0,0.14)" />

        <text x="76" y="92" fill="white" font-family="Arial, sans-serif" font-size="20" letter-spacing="3" opacity="0.86">PLAYER RECAP</text>
        <text x="76" y="188" fill="white" font-family="Arial, sans-serif" font-size="72" font-weight="900">${playerName}</text>
        <text x="76" y="236" fill="white" font-family="Arial, sans-serif" font-size="32" opacity="0.92">${teamName}</text>

        <rect x="76" y="276" width="380" height="44" rx="22" fill="url(#glass)" />
        <text x="98" y="305" fill="white" font-family="Arial, sans-serif" font-size="20" opacity="0.95">Ultimos jogos: ${badge}</text>

        <rect x="76" y="422" width="312" height="132" rx="20" fill="rgba(255,255,255,0.16)" />
        <rect x="444" y="422" width="312" height="132" rx="20" fill="rgba(255,255,255,0.16)" />
        <rect x="812" y="422" width="312" height="132" rx="20" fill="rgba(255,255,255,0.16)" />

        <text x="104" y="462" fill="white" font-family="Arial, sans-serif" font-size="20" opacity="0.88">Partidas</text>
        <text x="104" y="526" fill="white" font-family="Arial, sans-serif" font-size="64" font-weight="800">${recap.career.matches}</text>

        <text x="472" y="462" fill="white" font-family="Arial, sans-serif" font-size="20" opacity="0.88">Gols</text>
        <text x="472" y="526" fill="white" font-family="Arial, sans-serif" font-size="64" font-weight="800">${recap.career.goals}</text>

        <text x="840" y="462" fill="white" font-family="Arial, sans-serif" font-size="20" opacity="0.88">Assistencias</text>
        <text x="840" y="526" fill="white" font-family="Arial, sans-serif" font-size="64" font-weight="800">${recap.career.assists}</text>

        <text x="76" y="585" fill="white" font-family="Arial, sans-serif" font-size="16" opacity="0.70">Generated by VARzea</text>
        <text x="1002" y="585" text-anchor="end" fill="white" font-family="Arial, sans-serif" font-size="16" opacity="0.70">player summary</text>
      </svg>
    `;

    return svgResponse(svg);
  } catch {
    return svgResponse(
      `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#0f172a"/><text x="600" y="320" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="48" font-weight="700">Recap indisponivel no momento</text></svg>`
    );
  }
}
