import type { Role, Permission } from "./types";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: [
    "match:view", "match:create", "match:edit", "match:delete",
    "lineup:view", "lineup:manage", "lineup:publish",
    "rsvp:view", "rsvp:respond", "rsvp:manage",
    "player:view", "player:create", "player:edit", "player:delete",
    "finance:view", "finance:manage", "finance:view_own",
    "equipment:view", "equipment:manage",
    "evaluation:view", "evaluation:create", "evaluation:view_own",
    "fine:view", "fine:create", "fine:manage",
    "rule:view", "rule:manage",
    "message:view", "message:create", "message:manage",
    "poll:view", "poll:vote", "poll:create", "poll:manage",
    "gallery:view", "gallery:upload", "gallery:manage",
    "season:view", "season:manage",
    "report:view", "report:view_financial",
    "team:view", "team:manage",
    "friendly_request:view", "friendly_request:manage",
    "recruitment:view", "recruitment:manage",
    "tactical:view", "tactical:manage",
    "notification:view", "notification:manage"
  ],
  COACH: [
    "match:view", "match:create", "match:edit", "match:delete",
    "lineup:view", "lineup:manage", "lineup:publish",
    "rsvp:view", "rsvp:respond", "rsvp:manage",
    "player:view", "player:edit",
    "finance:view", "finance:view_own",
    "equipment:view",
    "evaluation:view", "evaluation:create", "evaluation:view_own",
    "fine:view", "fine:create", "fine:manage",
    "rule:view",
    "message:view", "message:create", "message:manage",
    "poll:view", "poll:vote", "poll:create", "poll:manage",
    "gallery:view", "gallery:upload", "gallery:manage",
    "season:view", "season:manage",
    "report:view",
    "team:view",
    "friendly_request:view",
    "recruitment:view",
    "tactical:view", "tactical:manage",
    "notification:view", "notification:manage"
  ],
  MATERIAL_DIRECTOR: [
    "match:view",
    "lineup:view",
    "rsvp:view", "rsvp:respond",
    "player:view",
    "finance:view", "finance:view_own",
    "equipment:view", "equipment:manage",
    "evaluation:view", "evaluation:view_own",
    "fine:view",
    "rule:view",
    "message:view",
    "poll:view", "poll:vote",
    "gallery:view", "gallery:upload", "gallery:manage",
    "season:view",
    "report:view",
    "team:view",
    "friendly_request:view",
    "recruitment:view",
    "tactical:view",
    "notification:view", "notification:manage"
  ],
  PLAYER: [
    "match:view",
    "lineup:view",
    "rsvp:view", "rsvp:respond",
    "player:view",
    "finance:view_own",
    "equipment:view",
    "evaluation:view_own",
    "fine:view",
    "rule:view",
    "message:view",
    "poll:view", "poll:vote",
    "gallery:view", "gallery:upload",
    "season:view",
    "team:view",
    "friendly_request:view",
    "recruitment:view",
    "tactical:view",
    "notification:view"
  ]
};
